controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rotor_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints: 
      - J2_A_rotor
    
    interface_name: position
